[package]
name = "devp2p"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Rust devp2p binary executable"
default-run = "devp2p"

[dependencies]
# reth
reth-fs-util.workspace = true
reth-primitives.workspace = true
reth-network.workspace = true
reth-network-types.workspace = true

# misc
clap = { workspace = true, features = ["derive", "env"] }
eyre.workspace = true
secp256k1 = { workspace = true, features = ["global-context", "rand-std", "recovery"] }
enr = { version = "0.12.0", default-features = false, features = [
    "k256",
    "rust-secp256k1",
] }
